CREATE DATABASE IF NOT EXISTS YadoDB;

USE YadoDB;

CREATE TABLE Roles (
    ID INT PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Description VARCHAR(100) NOT NULL
);

CREATE TABLE Users (
    UUID VARCHAR(36) PRIMARY KEY,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    Password VARCHAR(50) NOT NULL,
    Gender CHAR NULL,
    ImageProfile VARBINARY(8000) NULL,
    RoleId INT DEFAULT 1,
    FOREIGN KEY (RoleId) REFERENCES Roles(ID) ON UPDATE CASCADE ON DELETE CASCADE
);


CREATE TABLE Countries (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(50) NOT NULL
);

CREATE TABLE States (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(200) NOT NULL,
    CountryId INT,
    FOREIGN KEY (CountryId) REFERENCES Countries(ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Populations (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    StateId INT,
    FOREIGN KEY (StateId) REFERENCES States(ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Hotels (
    UUID VARCHAR(36) PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Description VARCHAR(1500) NOT NULL,
    Stars INT NOT NULL, 
    Address VARCHAR(50) NOT NULL,
    Latitude FLOAT NOT NULL,
    Longitude FLOAT NOT NULL,
    NumVisited INT DEFAULT 0 NULL,
    PopulationId INT,
    FOREIGN KEY (PopulationId) REFERENCES Populations(ID) ON UPDATE CASCADE ON DELETE CASCADE
);


CREATE TABLE Owners (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    UserUuid VARCHAR(40),
    HotelUuid VARCHAR(40),
    FOREIGN KEY (UserUuid) REFERENCES Users(UUID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (HotelUuid) REFERENCES Hotels(UUID) ON UPDATE CASCADE ON DELETE CASCADE
);


CREATE TABLE Favorites (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    UserUuid VARCHAR(40),
    HotelUuid VARCHAR(40),
    FOREIGN KEY (UserUuid) REFERENCES Users(UUID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (HotelUuid) REFERENCES Hotels(UUID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Reviews (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Qualification FLOAT NOT NULL,
    PositiveComment VARCHAR(200) NOT NULL,
    NegativeComment VARCHAR(200) NULL,
    UserId VARCHAR(40),
    HotelUuid VARCHAR(40),
    FOREIGN KEY (UserId) REFERENCES Users(UUID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (HotelUuid) REFERENCES Hotels(UUID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Images (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Image VARCHAR(200) NOT NULL,
    Description VARCHAR(200) NOT NULL,
    HotelUuid VARCHAR(40),
    FOREIGN KEY (HotelUuid) REFERENCES Hotels(UUID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Companies (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Url VARCHAR(200) NOT NULL,
    LogoImg VARCHAR(200) NOT NULL
);

CREATE TABLE Sites (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    UrlOrigin VARCHAR(200) NOT NULL,
    NightlyPrice FLOAT NOT NULL,
    HotelUuid VARCHAR(40),
    CompanyId INT,
    FOREIGN KEY (HotelUuid) REFERENCES Hotels(UUID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (CompanyId) REFERENCES Companies(ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Parameters (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ReviewScore FLOAT,
    BeachDistance FLOAT DEFAULT 0 NOT NULL,
    CenterDistance FLOAT DEFAULT 0 NOT NULL,
    BicycleRental TINYINT DEFAULT 0 NOT NULL,
    Solarium TINYINT DEFAULT 0 NOT NULL,
    GolfCourse TINYINT DEFAULT 0 NOT NULL,
    Massage TINYINT DEFAULT 0 NOT NULL,
    FitnessCentre TINYINT DEFAULT 0 NOT NULL,
    FreeCancellation TINYINT DEFAULT 0 NOT NULL,
    SelfCatering TINYINT DEFAULT 0 NOT NULL,
    BreakfastIncluded TINYINT DEFAULT 0 NOT NULL,
    BreakfastDinnerIncluded TINYINT DEFAULT 0 NOT NULL,
    TwinBeds TINYINT DEFAULT 0 NOT NULL,
    DoubleBed TINYINT DEFAULT 0 NOT NULL,
    LargeDoubleBed TINYINT DEFAULT 0 NOT NULL,
    ExtraLargeDoubleBed TINYINT DEFAULT 0 NOT NULL,
    NonSmokingRooms TINYINT DEFAULT 0 NOT NULL,
    Parking TINYINT DEFAULT 0 NOT NULL,
    VeryGoodWifi TINYINT DEFAULT 0 NOT NULL,
    FamilyRooms TINYINT DEFAULT 0 NOT NULL,
    SwimmingPool TINYINT DEFAULT 0 NOT NULL,
    RoomService TINYINT DEFAULT 0 NOT NULL,
    PetsAllowed TINYINT DEFAULT 0 NOT NULL,
    FacilitesDisabledGuest TINYINT DEFAULT 0 NOT NULL,
    SpaWellnessCentre TINYINT DEFAULT 0 NOT NULL,
    AeroportSchuttle TINYINT DEFAULT 0 NOT NULL,
    Restaurant TINYINT DEFAULT 0 NOT NULL,
    ReceptionAlwaysOpen TINYINT DEFAULT 0 NOT NULL,
    Kitchen TINYINT DEFAULT 0 NOT NULL,
    PrivateBathroom TINYINT DEFAULT 0 NOT NULL,
    AirConditioning TINYINT DEFAULT 0 NOT NULL,
    LaptopFriendlyWorkspace TINYINT DEFAULT 0 NOT NULL,
    Bath TINYINT DEFAULT 0 NOT NULL,
    PrivatePool TINYINT DEFAULT 0 NOT NULL,
    Terrace TINYINT DEFAULT 0 NOT NULL,
    Balcony TINYINT DEFAULT 0 NOT NULL,
    BlatScreenTv TINYINT DEFAULT 0 NOT NULL,
    WashingMachine TINYINT DEFAULT 0 NOT NULL,
    Patio TINYINT DEFAULT 0 NOT NULL,
    Soundproofing TINYINT DEFAULT 0 NOT NULL,
    ViewHotel TINYINT DEFAULT 0 NOT NULL,
    SeaView TINYINT DEFAULT 0 NOT NULL,
    WheelchairAccessible TINYINT DEFAULT 0 NOT NULL,
    ToiletGrabRails TINYINT DEFAULT 0 NOT NULL,
    HigherLevelToilet TINYINT DEFAULT 0 NOT NULL,
    LowerBathroomSink TINYINT DEFAULT 0 NOT NULL,
    EmergencyCordBathroom TINYINT DEFAULT 0 NOT NULL,
    VisualAidsBraille TINYINT DEFAULT 0 NOT NULL,
    VisualAidsTactileSigns TINYINT DEFAULT 0 NOT NULL,
    HotelUuid VARCHAR(40),
    FOREIGN KEY (HotelUuid) REFERENCES Hotels(UUID) ON UPDATE CASCADE ON DELETE CASCADE
);
